CREATE TABLE T_MESSURE(
  ID_MESSURE INT NOT NULL ENABLE,
  NAME VARCHAR2(4) NOT NULL ENABLE,
  CONSTRAINT PK_MESSURE PRIMARY KEY (ID_MESSURE) ENABLE
)

CREATE TABLE T_MATERIAL(
  ID_MATERIAL INT NOT NULL ENABLE,
  NAME VARCHAR2(100) NOT NULL ENABLE,
  ID_MESSURE INT NOT NULL ENABLE,
  CONSTRAINT PK_MATERIAL PRIMARY KEY (ID_MATERIAL) ENABLE,
  CONSTRAINT FK_MATERIAL_MESSURE FOREIGN KEY (ID_MESSURE) REFERENCES T_MESSURE (ID_MESSURE) ENABLE
)

CREATE TABLE T_INPRICE(
  ID_MATERIAL INT NOT NULL ENABLE,
  PRICE_DATE DATE NOT NULL ENABLE,
  PRICE NUMBER(10,2) CHECK (PRICE>=0) ENABLE,
  CONSTRAINT FK_INPRICE_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE
)

CREATE TABLE T_CATERER(
  ID_CATERER INT NOT NULL ENABLE,
  NAME VARCHAR2(100) NOT NULL ENABLE,
  ADDRESS VARCHAR2(150),
  PHONE INT NOT NULL ENABLE,
  FAX INT,
  CONSTRAINT PK_CATERER PRIMARY KEY (ID_CATERER) ENABLE
)

CREATE TABLE T_STORE(
  ID_STORE INT NOT NULL ENABLE,
  NAME VARCHAR2(100) NOT NULL ENABLE,
  CONSTRAINT PK_STORE PRIMARY KEY (ID_STORE) ENABLE
)

CREATE TABLE T_SUPPLY(
  ID_SUPPLY INT NOT NULL ENABLE,
  ID_CATERER INT NOT NULL ENABLE,
  ID_MATERIAL INT NOT NULL ENABLE,
  ID_STORE INT NOT NULL ENABLE,
  SUPPLY_DATE DATE NOT NULL ENABLE,
  VOLUME INT NOT NULL ENABLE,
  CONSTRAINT PK_SUPPLY PRIMARY KEY (ID_SUPPLY),
  CONSTRAINT FK_SUPPLY_CATERER FOREIGN KEY (ID_CATERER) REFERENCES T_CATERER(ID_CATERER),
  CONSTRAINT FK_SUPPLY_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL),
  CONSTRAINT FK_SUPPLY_STORY FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE)
) 

CREATE TABLE T_SURPULS(
  ID_MATERIAL INT NOT NULL,
  ID_STORE INT NOT NULL,
  VOLUME INT CHECK (VOLUME >= 0),
  CONSTRAINT FK_SURPLUS_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE,
  CONSTRAINT FK_SURPLUS_STORE FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE) ON DELETE CASCADE
)

CREATE TABLE T_EMPLOYER(
  ID_EMPLOYER INT NOT NULL,
  SURNAME NVARCHAR2(30) NOT NULL,
  NAME NVARCHAR2(30) NOT NULL,
  FATHER_NAME NVARCHAR2(30),
  CONSTRAINT PK_EMPLOYER PRIMARY KEY (ID_EMPLOYER)
)

CREATE TABLE T_SECTION(
  ID_SECTION INT NOT NULL,
  NAME NVARCHAR2(100) NOT NULL,
  ID_EMPLOYER INT NOT NULL,
  CONSTRAINT PK_SECTION PRIMARY KEY (ID_SECTION),
  CONSTRAINT FK_SECTION_EMPLOYER FOREIGN KEY (ID_EMPLOYER) REFERENCES T_EMPLOYER(ID_EMPLOYER) ON DELETE CASCADE
)

CREATE TABLE T_DELIVER(
  ID_DELIVER INT NOT NULL,
  ID_SECTION INT NOT NULL,
  ID_MATERIAL INT NOT NULL,
  ID_STORE INT NOT NULL,
  DELIVER_DATE DATE NOT NULL,
  CONSTRAINT PK_DELIVER PRIMARY KEY (ID_DELIVER),
  CONSTRAINT FK_DELIVER_SECTION FOREIGN KEY (ID_SECTION) REFERENCES T_SECTION(ID_SECTION) ON DELETE CASCADE,
  CONSTRAINT FK_DELIVER_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES T_MATERIAL(ID_MATERIAL) ON DELETE CASCADE,
  CONSTRAINT FK_DELIVER_STORE FOREIGN KEY (ID_STORE) REFERENCES T_STORE(ID_STORE) ON DELETE CASCADE
)

-- 2
ALTER TABLE T_CATERER
  DROP COLUMN ADDRES;
ALTER TABLE T_CATERER
  ADD (LEGAL_ADRESS NVARCHAR2(150) NOT NULL,
    PHYSICAL_Adders NVARCHAR2(150) NOT NULL,
    E_MAIL NVARCHAR2(50));

-- 3
  ALTER TABLE T_INPRICE
  ADD CONSTRAINT PK_INPRICE PRIMARY KEY (ID_MATERIAL, PRICE_DATE);

-- 4
CREATE TABLE T_GROUP(
  ID_GROUP INT NOT NULL,
  NAME NVARCHAR2(40) NOT NULL,
  CONSTRAINT PK_GROUP PRIMARY KEY (ID_GROUP)
);

ALTER TABLE T_MATERIAL
  ADD ID_GROUP INT
  ADD CONSTRAINT FK_MATERIAL_GROUP FOREIGN KEY (ID_GROUP) REFERENCES T_GROUP(ID_GROUP) ON DELETE SET NULL;

-- 5
ALTER TABLE T_SUPPLY
  MODIFY (VOLUME INT CHECK (VOLUME >= 0))